spring:
  datasource:
    username: postgres
    password: post
    url: jdbc:postgresql://localhost:5432/postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 998877485668-v28cb0ruuueoqsgfu4hqmojm1jp8lito.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 993487071672857
            client-secret: 79f5c63b8c73c943df1b5d49cb835fa9

